# Generated by Django 4.0 on 2021-12-22 10:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('accounting', '0003_alter_mark_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classes.schoolclass')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceInSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveIntegerField(choices=[(1, 'Понеділок'), (2, 'Вівторок'), (3, 'Середа'), (4, 'Четвер'), (5, "П'ятниця"), (6, 'Субота')])),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.classschedule')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.classsubject')),
            ],
        ),
        migrations.AddConstraint(
            model_name='placeinschedule',
            constraint=models.UniqueConstraint(fields=('schedule', 'number', 'day_of_week'), name='Два уроки не можуть проводитися одночасно'),
        ),
    ]
